# Generated by Django 5.2.1 on 2025-05-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
    ]
